# GitHub Labels Definition
# Synced by crazy-max/ghaction-github-labeler

# Type Labels
- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: enhancement
  color: "a2eeef"
  description: New feature or request

- name: refactor
  color: "7057ff"
  description: Code improvement without changing functionality

- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation

- name: dependencies
  color: "ffc107"
  description: Dependency updates

- name: chore
  color: "bfd4f2"
  description: Maintenance tasks
